[profile.default]
src = "src"
out = "out"
lib = ["lib"]
via_ir = true
optimizer_runs = 100
remappings = [
    'forge-std/=lib/forge-std/src/'
]

[invariant]
runs = 128
depth = 1000
fail_on_revert = false

# [coverage]
# via_ir = true
# See more config options https://github.com/foundry-rs/foundry/tree/master/config
